name: innitP2P
on: page_build
jobs:
  innit-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: innit-client
        run: node ./index.js
  innit-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: innit-client
        working-directory: ./react-gun/src
        run: npm start
