name: innitP2P
on: page_build
jobs:
  innit-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm start

  innit-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          cd react-gun/src
          npm start
