name: innitP2P
on: page_build
jobs:
  GUNserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: innitServer
        run: |
          npm install -g node
          node ./index.js
      - name: innitClient
        working-directory: ./react-gun/src
        run: npm start
